/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2024-02-03 07:37:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

  // Servletのデータ受け取り
  request.setCharacterEncoding("UTF8");
  String strName = (String) request.getAttribute("name");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>Insert</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t<!-- css読みこみ -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- フッター CSS -->\r\n");
      out.write("    <link href=\"css/sticky-footer.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("    .hidden {\r\n");
      out.write("      display: none; /* 初期状態では非表示 */\r\n");
      out.write("    }\r\n");
      out.write("    .btnhidden_off {\r\n");
      out.write("      display: none; /* 初期状態では非表示 */\r\n");
      out.write("    }\r\n");
      out.write("    .fixed-label-width {\r\n");
      out.write("      width: 100px; /* ラベルの固定サイズを指定 */\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<header class=\"navbar navbar-expand-md navbar\" style=\"background-color: #e3f2fd;\">\r\n");
      out.write("\r\n");
      out.write("\t    <nav class=\"container-xxl flex-wrap flex-md-nowrap\" aria-label=\"Main navigation\">\r\n");
      out.write("\r\n");
      out.write("\t    <div class=\"collapse navbar-collapse\" id=\"bdNavbar\">\r\n");
      out.write("\t      <form id=\"fm_menu\" action=\"/admin/MenuController\" method=\"Post\">\r\n");
      out.write("\t      <ul class=\"navbar-nav flex-row flex-wrap bd-navbar-nav pt-2 py-md-0\">\r\n");
      out.write("\t        <li class=\"nav-item col-6 col-md-auto\">\r\n");
      out.write("\t          <button class=\"nav-link p-2\" onclick=\"exec()\" name=\"name\" value=\"menu\">メニュー</button>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li class=\"nav-item col-6 col-md-auto\">\r\n");
      out.write("\t          <button class=\"nav-link p-2\" onclick=\"exec()\" name=\"name\" value=\"meet\">面談登録</button>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li class=\"nav-item col-6 col-md-auto\">\r\n");
      out.write("\t          <button class=\"nav-link p-2\" onclick=\"exec()\" name=\"name\" value=\"shokai\">社員照会</button>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li class=\"nav-item col-6 col-md-auto\">\r\n");
      out.write("\t          <button class=\"nav-link p-2 active\"  aria-current=\"true\" onclick=\"exec()\" name=\"name\" value=\"insert\">社員登録</button>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li class=\"nav-item col-6 col-md-auto\">\r\n");
      out.write("\t          <a class=\"nav-link p-2\"  onclick=\"ga('send', 'event', 'Navbar', 'Community links', 'Themes');\" target=\"_blank\" rel=\"noopener\">-----</a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li class=\"nav-item col-6 col-md-auto\">\r\n");
      out.write("\t          <a class=\"nav-link p-2\"  onclick=\"ga('send', 'event', 'Navbar', 'Community links', 'Blog');\" target=\"_blank\" rel=\"noopener\">-----</a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t      </ul>\r\n");
      out.write("\t\t  </form>\r\n");
      out.write("\t      <hr class=\"d-md-none text-white-50\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t      <form id=\"fm\" action=\"/admin/MainController\" method=\"Get\">\r\n");
      out.write("\r\n");
      out.write("\t      <ul class=\"navbar-nav flex-row ml-md-auto d-none d-md-flex\">\r\n");
      out.write("\r\n");
      out.write("\t        <li class=\"nav-item dropdown\">\r\n");
      out.write("              <a class=\"nav-item nav-link dropdown-toggle mr-md-2\" href=\"#\" id=\"lang\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("              ");
      out.print(strName );
      out.write("さん\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"lang\">\r\n");
      out.write("                <a class=\"dropdown-item active\" href=\"/docs/4.3/\"> ");
      out.print(strName );
      out.write("さん </a>\r\n");
      out.write("                <a id=\"logout\" class=\"dropdown-item\">ログアウト</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\t      </ul>\r\n");
      out.write("\r\n");
      out.write("    \t  </form>\r\n");
      out.write("        </div>\r\n");
      out.write("  \t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-xxl bd-gutter mt-3 my-md-4 bd-layout\">\r\n");
      out.write("\t<h2>社員情報を登録</h2>\r\n");
      out.write("\r\n");
      out.write("\t<form id=\"fm_insert\" action=\"/admin/InsEmpController\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div class=\"input-group\">\r\n");
      out.write("          <label class=\"input-group-text fixed-label-width\" >社員番号</label>\r\n");
      out.write("          <input type=\"text\" name=\"emp_id\" id=\"input_id\" class=\"form-control\" placeholder=\"社員番号を６桁の半角数字で入力してください　例 203001\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("\t\t<div class=\"input-group\">\r\n");
      out.write("          <label class=\"input-group-text fixed-label-width\" > 名　前 </label>\r\n");
      out.write("          <input type=\"text\" name=\"name\" id=\"input_name\" class=\"form-control\" placeholder=\"名前を入力してください　例 出板　菜園酢\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("          <label class=\"input-group-text fixed-label-width\" > カ　ナ </label>\r\n");
      out.write("          <input type=\"text\" name=\"kana\" id=\"input_kana\" class=\"form-control\" placeholder=\"カナ名を入力してください　例　データ　サイエンス\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("\t\t<p>役職：<input class=\"form-check-input\" type=\"checkbox\" name=\"director\"></p>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"input-group\">\r\n");
      out.write("          <label class=\"input-group-text fixed-label-width\" for=\"department\"> 所　属 </label>\r\n");
      out.write("          <select class=\"form-select\" id=\"department\" name=\"department\">\r\n");
      out.write("            <option selected value=\"0\">所属...</option>\r\n");
      out.write("            <!-- 出来ればDBから持ってくる -->\r\n");
      out.write("            <option value=\"1\">事業推部</option>\r\n");
      out.write("            <option value=\"2\">営業部</option>\r\n");
      out.write("            <option value=\"3\">運用技術部/運用1課</option>\r\n");
      out.write("            <option value=\"4\">運用技術部/運用2課</option>\r\n");
      out.write("            <option value=\"5\">運用技術部/運用3課</option>\r\n");
      out.write("            <option value=\"6\">基盤技術部/基盤1課</option>\r\n");
      out.write("            <option value=\"7\">基盤技術部/基盤2課</option>\r\n");
      out.write("            <option value=\"8\">第1開発部/開発1課</option>\r\n");
      out.write("            <option value=\"9\">第1開発部/開発2課</option>\r\n");
      out.write("            <option value=\"10\">第1開発部/開発3課</option>\r\n");
      out.write("            <option value=\"11\">第2開発部/開発1課</option>\r\n");
      out.write("            <option value=\"12\">ビジネス推進</option>\r\n");
      out.write("          </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("        <p>管理者として登録する：<input class=\"form-check-input\" type=\"checkbox\" id=\"toggleCheckbox\" onchange=\"toggleVisibility()\" name=\"admincheck\"></p>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"dataToToggle\" class=\"hidden\">\r\n");
      out.write("          <!-- ここに表示・非表示させるデータを追加 -->\r\n");
      out.write("          <div class=\"input-group\">\r\n");
      out.write("            <label class=\"input-group-text fixed-label-width\" >パスワード</label>\r\n");
      out.write("            <input type=\"text\" name=\"pass\" id=\"input_pass\" class=\"form-control\" placeholder=\"ログイン用のパスワードを入力してください\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <br>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <p><button  class=\"btn btn-primary\" id=\"btnins\" name=\"ins\" onclick=\"exec()\">社員情報を登録する</button></p>\r\n");
      out.write("        <p><button  class=\"btn btn-success btnhidden_off\" id=\"btnupd\" name=\"upd\" onclick=\"exec()\">社員情報を更新する</button></p>\r\n");
      out.write("        <p><button  class=\"btn btn-danger btnhidden_off\" id=\"btndel\" name=\"del\" onclick=\"exec()\">社員情報を削除する</button></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <p>登録した社員の情報を更新する場合は以下のテーブルから参照し編集ボタンをクリックしてください。</p>\r\n");
      out.write("\t<form id=\"fm\" action=\"/admin/MenuController\" method=\"Get\">\r\n");
      out.write("\r\n");
      out.write("            ");
 int count = (int) request.getAttribute("count"); 
      out.write("\r\n");
      out.write("            <table class=\"table table-striped\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th scope=\"col\">社員番号</th>\r\n");
      out.write("                    <th scope=\"col\">名前</th>\r\n");
      out.write("                    <th scope=\"col\">カナ</th>\r\n");
      out.write("                    <th scope=\"col\"></th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            ");
 for (int i = 0; i < count; i++) { 
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td scope=\"row\" class=\"id\">");
      out.print( ((String[])(request.getAttribute("resID")))[i] );
      out.write("</td>\r\n");
      out.write("                    <td scope=\"row\" class=\"name\">");
      out.print( ((String[])(request.getAttribute("resName")))[i] );
      out.write("</td>\r\n");
      out.write("                    <td scope=\"row\" class=\"kana\">");
      out.print( ((String[])(request.getAttribute("resKananame")))[i] );
      out.write("</td>\r\n");
      out.write("                    <td scope=\"row\"><button type=\"button\" class=\"selectBtn btn btn-success\">編集</button></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("      <div class=\"container text-center\">\r\n");
      out.write("        <p class=\"text-muted\">Data Sience Co.LTD</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<!-- js読みこみ -->\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("        $(\".selectBtn\").on(\"click\", selectBtn);\r\n");
      out.write("    });\r\n");
      out.write("\tfunction selectBtn() {\r\n");
      out.write("\t\tvar name0 = $(this).closest('tr').find('.id').text();\r\n");
      out.write("        $(\"#input_id\").val(name0);\r\n");
      out.write("\t\tvar name1 = $(this).closest('tr').find('.name').text();\r\n");
      out.write("        $(\"#input_name\").val(name1);\r\n");
      out.write("        var name2 = $(this).closest('tr').find('.kana').text();\r\n");
      out.write("        $(\"#input_kana\").val(name2);\r\n");
      out.write("\r\n");
      out.write("        var btnins = document.getElementById('btnins');\r\n");
      out.write("        var btnupd = document.getElementById('btnupd');\r\n");
      out.write("        var btndel = document.getElementById('btndel');\r\n");
      out.write("        btnins.style.display = 'none';\r\n");
      out.write("        btnupd.style.display = 'block';\r\n");
      out.write("        btndel.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction exec() {\r\n");
      out.write("\t\tdocument.getElementById(\"fm_insert\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction toggleVisibility() {\r\n");
      out.write("\t  var dataElement = document.getElementById('dataToToggle');\r\n");
      out.write("\t  var checkbox = document.getElementById('toggleCheckbox');\r\n");
      out.write("\r\n");
      out.write("\t  // チェックボックスがチェックされていれば表示、そうでなければ非表示\r\n");
      out.write("\t  dataElement.style.display = checkbox.checked ? 'block' : 'none';\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
